Papirnyk_Oleksandr/PollCreator/PollCreator/Controllers/PollBuilderController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PollCreator.Interfaces.Services;
using PollCreator.Models;
using PollCreator.ViewModels;

namespace PollCreator.Controllers
{
	[Route("~/p/")]
	public class PollBuilderController : Controller
	{
		private readonly ITokenService _tokenService;
		private readonly IPollRepository _pollRepository;
		private readonly IPollOptionRepository _pollOptionRepository;
		private readonly IRequestHeaderHandler _requestHeaderHandler;

		public PollBuilderController(ITokenService tokenService, IPollRepository pollRepository,
			IPollOptionRepository pollOptionRepository, IRequestHeaderHandler requestHeaderHandler)
		{
			_tokenService = tokenService;
			_pollRepository = pollRepository;
			_pollOptionRepository = pollOptionRepository;
			_requestHeaderHandler = requestHeaderHandler;
		}

		[Route("create")]
		[HttpGet]
		public async Task<RedirectToActionResult> Create()
		{
			string pollToken = _tokenService.GetRandomToken(6);
			string editorToken = _tokenService.GetRandomToken(32);

			await _pollRepository.Insert(new PollDto
			{
				Title = null,
				IsSingleOption = null,
				PollId = pollToken,
				EditorToken = editorToken,
				IsPublished = false
			});
			
			return RedirectToAction("Edit",new
			{
				pollId = pollToken,
				editorId = editorToken
			});

		}

		[Route("{pollId}/edit/{editorId}")]
		[HttpGet]
		public async Task<IActionResult> Edit(string pollId, string editorId)
		{
			var pollDto = await _pollRepository.Select(pollId);
			PollBuilderViewModel pollBuilderViewModel = new PollBuilderViewModel
			{
				PollId = pollId,
				EditorToken = editorId,
				Host = _requestHeaderHandler.GetHost(ControllerContext)
			};

			if (pollDto == null)
			{
				return NotFound();
			}
			if (pollDto.EditorToken != editorId)
			{
				return BadRequest();
			}
			if (pollDto.IsPublished) 
			{
				pollBuilderViewModel = new PollBuilderViewModel()
				{
					Title = pollDto.Title,
					IsSingleOption = pollDto.IsSingleOption,
					IsPublished = pollDto.IsPublished,
					PollId = pollDto.PollId,
					EditorToken = pollDto.EditorToken,
					Options = await _pollOptionRepository.SelectAllForPollPk(pollDto.PrimaryKey),
					Host = _requestHeaderHandler.GetHost(ControllerContext)
				};
			}
			return View("Edit", pollBuilderViewModel);
		}

		[HttpPost]
		[Route("publish")]
		public async Task<IActionResult> Publish([FromBody]PollPublishRequest pollPublishRequest)
		{
			if (!ModelState.IsValid)
			{
				return BadRequest();
			}

			var pollDto = await _pollRepository.Select(pollPublishRequest.PollId);

			if (!pollDto.IsPublished)
			{
				pollDto.IsPublished = true;
				pollDto.Title = pollPublishRequest.Title;
				pollDto.IsSingleOption = pollPublishRequest.IsSingleOption;
				pollDto.Options = pollPublishRequest.Options;
				await _pollRepository.Update(pollDto);
				await _pollOptionRepository.Insert(pollPublishRequest.Options, pollDto.PrimaryKey);
			}
			else
			{
				return BadRequest();
			}


			return Ok();
		}
	}
}

Papirnyk_Oleksandr/PollCreator/PollCreator/Controllers/PollRendererController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PollCreator.Interfaces.Services;
using PollCreator.Models;
using PollCreator.ViewModels;

namespace PollCreator.Controllers
{
	[Route("~/p/")]
	public class PollRendererController : Controller
	{
		private readonly IPollRepository _pollRepository;
		private readonly IPollOptionRepository _pollOptionRepository;
		private readonly IVoteRepository _voteRepository;
		private readonly IRequestHeaderHandler _requestHeaderHandler;

		public PollRendererController(IPollRepository pollRepository, IPollOptionRepository pollOptionRepository,
			IVoteRepository voteRepository, IRequestHeaderHandler requestHeaderHandler)
		{
			_pollRepository = pollRepository;
			_pollOptionRepository = pollOptionRepository;
			_voteRepository = voteRepository;
			_requestHeaderHandler = requestHeaderHandler;
		}

		[Route("{pollId}")]
		[HttpGet]
		public async Task<IActionResult> RenderVotePage([FromRoute]string pollId)
		{
			PollDto pollDto = await _pollRepository.Select(pollId);

			if (pollDto == null)
			{
				return NotFound();
			}

			bool hasVoted = CheckIfUserHasVoted(pollId);

			PollRenderViewModel pollRenderViewModel = new PollRenderViewModel()
			{
				Title = pollDto.Title,
				IsSingleOption = Convert.ToBoolean(pollDto.IsSingleOption),
				Options = await _pollOptionRepository.SelectAllForPollPk(pollDto.PrimaryKey),
				PollId = pollDto.PollId,
				HasVoted = hasVoted
			};

			return View("RenderVotePage", pollRenderViewModel);
		}

		[Route("submit")]
		[HttpPost]
		public async Task<IActionResult> SubmitVote([FromBody] VoteRequest voteRequest)
		{
			bool hasVoted = CheckIfUserHasVoted(voteRequest.PollId);

			if (hasVoted || !voteRequest.SelectedVotes.Any())
			{
				return BadRequest();
			}

			var userAgent = _requestHeaderHandler.GetHeader(ControllerContext, "User-Agent");
			var clientIp = _requestHeaderHandler.GetUserIp(ControllerContext);

			foreach (var vote in voteRequest.SelectedVotes)
			{
				if (vote.Value.Length >= 100)
				{
					vote.Value = vote.Value.Substring(0, 99);
				}
				vote.UserAgent = userAgent;
				vote.ClientIp = clientIp;
			}

			var pollDto = await _pollRepository.Select(voteRequest.PollId);

			if (pollDto == null)
			{
				return NotFound();
			}


			Response.Cookies.Append(voteRequest.PollId, voteRequest.PollId,
				new CookieOptions()
				{
					Expires = DateTime.Now.AddDays(1)
				});
			await _voteRepository.Insert(voteRequest.SelectedVotes.ToList(), pollDto.PrimaryKey);

			return Ok();
		}

		private bool CheckIfUserHasVoted(string pollId)
		{
			bool hasVoted = false;
			var cookieValue = _requestHeaderHandler.GetCookie(ControllerContext, pollId);

			if (cookieValue == pollId)
			{
				hasVoted = true;
			}

			return hasVoted;
		}

		[Route("renderChart")]
		[HttpPost]
		public async Task<IActionResult> RenderPieChart([FromBody] PieChartRequest request)
		{
			bool hasVoted = CheckIfUserHasVoted(request.PollId);

			if (!hasVoted)
			{
				return StatusCode(418);
			}

			var pollDto = await _pollRepository.Select(request.PollId);

			if (pollDto == null)
			{
				return NotFound();
			}

			var votes = await _voteRepository.CountVotes(pollDto.PrimaryKey);

			return new JsonResult(new PieChartDto
			{
				Votes = votes
			});
		}

	}
}

Papirnyk_Oleksandr/PollCreator/PollCreator/Views/PollRenderer/RenderVotePage.cshtml
@model PollCreator.ViewModels.PollRenderViewModel
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="/css/votePage.css">
	<title>Vote Page</title>
</head>
<body>
<div style="width: 100%;">
	<ul class="headerUl">
		<li class="headerLi"><a asp-action="Index" asp-controller="Home">Home Page</a></li>
		<li class="headerLi"><a asp-action="Create" asp-controller="PollBuilder">Create Another Poll</a></li>
	</ul>
</div>
<div class="subTitle">
	@Html.DisplayName(Model.Title)
</div>
<div class="container">
	@{
		using (Html.BeginForm("SubmitVote", "PollRenderer", FormMethod.Post, new {id = "voteForm", @class = "voteForm position__absolute"}))
		{
			<div class="voteElementsContainer">
				@if (Model.IsSingleOption)
				{
					foreach (var option in Model.Options)
					{
						<div class="radiobtn">
							<input id=@option.SerialNumber name="radioBtn" type="radio" value="@option.Value"/>
							<label style="width: fit-content;" for="@option.SerialNumber"> @option.Value</label>
						</div>
					}
				}
				else
				{

					foreach (var option in Model.Options)
					{
						<div class="voteItemContainer">
							<div class="check">
								<input id=@option.SerialNumber name="@option.Value" type="checkbox" value="@option.Value"/>
								<label for="@option.SerialNumber"></label>
							</div>
							<span class="spanForCheckBox">@option.Value</span>
						</div>
					}
				}
			</div>
			<input asp-for="PollId" value="@Model.PollId"/>
			<input asp-for="HasVoted" value="@Model.HasVoted"/>
			<button class="votePageBtn" id="submitVote" type="button">Vote</button>
		}
	}
	<div class="chart-container">
		<canvas id="voteChart"></canvas>
	</div>
</div>
<span id="votesOnRender"></span>
<script src="/js/vote.js" type="module"></script>
</body>
</html>